### ISSUE TITLE
Feature Request: Server status command.

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/GeyserDiscordBot#102]
So I was thinking that you could add a server status command so you can detect what servers MOTD/Player Count/ Server Software. This command can detect both java and bedrock servers. I saw this idea in another server and thought it would be a nice fit for the bot.

**Example Usage:**
Java:
!status play.tydiumcraft.tk

Output:
![Screenshot_20210409-162104_Discord.jpg](https://user-images.githubusercontent.com/67938521/114236512-b4388080-994f-11eb-88f2-c73cae0d3cf6.jpg)

Bedrock (No server Icon):
!status be.tydiumcraft.tk:19132

Output: 
![Screenshot_20210409-162125_Discord.jpg](https://user-images.githubusercontent.com/67938521/114236571-c9151400-994f-11eb-8b13-b1692f345309.jpg)

Bedrock (with server icon):
!status be.tydiumcraft.tk:25562

Output:
![Screenshot_20210409-162136_Discord.jpg](https://user-images.githubusercontent.com/67938521/114236608-d9c58a00-994f-11eb-82b4-b2300468ea9b.jpg)

I hope this would be a nice fit for the bot in your eyes. Hope you enjoy!

**Comment by Chew** [comment]
As far as I know, this is a thing in the rewrite.

**Comment by Chew** [comment]
Indeed it is!
https://github.com/GeyserMC/GeyserDiscordBot/blob/jda/src/main/java/org/geysermc/discordbot/commands/PingCommand.java
Will keep open because it's not live technically.

**Comment by Tydium** [comment]
Awesome thanks!
