### ISSUE TITLE
Muting via mention doesn't work and the appeal link is shown when punishments are undone

### ISSUE THREAD

**Issue by EasyClifton** [GeyserMC/GeyserDiscordBot#158]
@rtm516 asked me to make these two one issue so here we go

**Issue 1:**
Muting doesn't work via mention

![](https://media.discordapp.net/attachments/614877230811709474/873522310877937684/Screenshot_20210807-140539_Discord-Beta.png)

**Issue 2:**
The appeal link is included in the unmute message (also the unmute message is red, shouldn't it be green?)

![](https://media.discordapp.net/attachments/746037590951592028/873522006535069696/Screenshot_20210807-140307_Discord-Beta.jpg)

**Comment by rtm516** [comment]
Closed with 6392d01
