### ISSUE TITLE
Feature Request: Update !provider WitherHosting

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/GeyserDiscordBot#165]
I work at witherhosting and would like to ask if you could please update the current command `!provider WitherHosting` with this -

Get geyser as a plugin. Put the port provided by the host in your config.yml for the java and bedrock sections, and you will be able to connect! Refer to the hosts support article for more - https://support.witherhosting.com/en/article/how-to-install-and-use-geysermc-1xn5l6v/

**Comment by Heath123** [comment]
All of these come from the wiki page at https://github.com/GeyserMC/Geyser/wiki/Supported-Hosting-Providers  which is publicly editable

**Comment by vijaypondini** [comment]
I just edited it, it reflects publically instantly? I'm surprised that anyone can edit, aren't we afraid someone deletes the text and saves it?

**Comment by Chew** [comment]
Yes, we get the providers each time the command is run, kinda inefficient but works. It wasn't showing up because you forgot to put the text within (parenthesis) that is required to parse correctly. Should be good now.

**Comment by Heath123** [comment]
> I'm surprised that anyone can edit, aren't we afraid someone deletes the text and saves it?

Well, that's how a wiki works...

**Comment by Heath123** [comment]
You can roll it back easily though
