### ISSUE TITLE
Feature Request: Support timeouts

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/GeyserDiscordBot#224]
Discord's semi-recent 'timeout' feature is currently unsupported by the bot. Similar to kicks and bans, timeouts should be logged in the specified log channel.
A timeout command could also be added, like kicks and bans have. I believe the API allows us to time out users for longer than the official client normally allows us to (28 days instead of 7).

**Comment by rtm516** [comment]
Added in 541eff7
