### ISSUE TITLE
Idea: Error analysis

### ISSUE THREAD

**Issue by Heath123** [GeyserMC/GeyserDiscordBot#6]
- Responds to common errors, like address in use errors
- Tells people when errors probably aren't caused by Geyser (when `org.geysermc` isn't mentioned in the stack trace)
- Send a link to the file and line the error comes from, to helps devs troubleshoot the problem
- Searches existing GitHub issues for the error

**Comment by rtm516** [comment]
Maybe use https://www.npmjs.com/package/java-stack-parser to parse the traces into a usable format

**Comment by Heath123** [comment]
I was using a regex but that would make more sense
