### ISSUE TITLE
Feature Request: More accurate regex for profanity filter

### ISSUE THREAD

**Issue by E404NNF** [GeyserMC/GeyserDiscordBot#90]
hey! it seems like that the bot doesn't detect profanity in URLs because of the regex.
Testing with ```new RegExp(`(?:|\W)foo(?:|\W)`)``` instead of ```new RegExp(`(^| )${Utils.escapeRegExp(newWord)}( |$)`)``` seems to work and detect URLs

**Comment by E404NNF** [comment]
i fucked up the formatting in the issue...

**Comment by rtm516** [comment]
Can you give some examples on how this is better?

**Comment by E404NNF** [comment]
Using the current regex: 
![img](https://astolfo.cummed-on.me/uploads/14d8db87-fd21-4d14-aadb-c1cb4bb9ede5/hHpkGfFP_.png)
Using the suggested regex:
![img](https://astolfo.cummed-on.me/uploads/14d8db87-fd21-4d14-aadb-c1cb4bb9ede5/9UwgC5JO_.png)

testing using [regexr](https://regexr.com/)

**Comment by Chew** [comment]
Images don't work.

**Comment by E404NNF** [comment]
> Images don't work.


I'll post another pics

**Comment by E404NNF** [comment]
Suggested regex:
![image](https://user-images.githubusercontent.com/37207067/122670688-ef66f380-d1cb-11eb-9b92-1a8d39281602.png)

Current one:

![image](https://user-images.githubusercontent.com/37207067/122670719-1c1b0b00-d1cc-11eb-8f2a-107466d770a7.png)

actually, thinking about it more, this doesn't really seem that more accurate...

**Comment by rtm516** [comment]
This would cause issues with stuff like `penistone` and `scunthorpe` along with other things. Hence why we only match whole words.
